FROM wmgroot/servicer-alpine

# gcloud sdk with kubectl
RUN wget https://dl.google.com/dl/cloudsdk/channels/rapid/google-cloud-sdk.zip
RUN unzip -q google-cloud-sdk.zip && rm google-cloud-sdk.zip
RUN google-cloud-sdk/install.sh --additional-components kubectl
ENV PATH $PATH:/google-cloud-sdk/bin

RUN gcloud --version
RUN gcloud auth configure-docker -q

# terraform
RUN wget https://releases.hashicorp.com/terraform/0.11.11/terraform_0.11.11_linux_amd64.zip
RUN unzip terraform_0.11.11_linux_amd64.zip && rm terraform_0.11.11_linux_amd64.zip
RUN mv terraform /usr/local/bin/
