FROM python:3.6-alpine

RUN apk update && apk upgrade && \
    apk add --no-cache bash docker git git-lfs openssh

RUN apk --no-cache add nodejs nodejs-npm yarn
RUN npm install -g typescript
ENV NODE_PATH $NODE_PATH:/usr/lib/node_modules

# install gcloud sdk on alpine
RUN wget https://dl.google.com/dl/cloudsdk/channels/rapid/google-cloud-sdk.zip
RUN unzip google-cloud-sdk.zip && rm google-cloud-sdk.zip
RUN google-cloud-sdk/install.sh --additional-components kubectl
ENV PATH $PATH:/google-cloud-sdk/bin

RUN gcloud --version
RUN gcloud auth configure-docker -q

RUN wget https://releases.hashicorp.com/terraform/0.11.10/terraform_0.11.10_linux_amd64.zip
RUN unzip terraform_0.11.10_linux_amd64.zip && rm terraform_0.11.10_linux_amd64.zip
RUN mv terraform /usr/local/bin/

ADD . /code/servicer/
RUN pip install -e /code/servicer
